### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by AndyCHENJUN** [RattyDAVE/privategpt#1]
Hi RattyDAVE,

Thanks for the docker image, it's easy to use privategpt. but I have a problem when I try to type something on the bottom txt tool bar. I got an 500 error as below information. Hope you could support me to fix this problem. Thank a lot.

Error getting data.<!doctype html> <html lang=en> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

**Comment by AndyCHENJUN** [comment]
My email address is andy.chenjun@gmail.com, looking forward to get your reply soon, Thanks.

**Comment by RattyDAVE** [comment]
I am unable to duplicate this.

Have you downloaded the model and given it time to load?

**Comment by AndyCHENJUN** [comment]
Thanks so much for your reply.
Yes, I do. I downloaded the model, but I don't know how many times I need to wait, not any notifications.
I have pull two times with two deffreent servers but no luck, each of time I met this problem. Could you please let me know what's your steps maybe I could do it as your steps to test it again. Thanks a lot.


one more thing, when I uploaded a excel file and I click 'Ingest Data' button, then I will got a failure message as below.

Unhandled Runtime Error
ReferenceError: response is not defined
"components/ConfigSideNav.js (27:3) @ response

  25 |   } catch (error) {
  26 |     setIsLoading(false);
> 27 | 	response.text().then(text => {toast.error("Error Ingesting data."+text);})
     | 	 ^
  28 |   }
  29 | };"

**Comment by AndyCHENJUN** [comment]
Dear Ratty,

Thanks so much for your reply.
Yes, I do. I downloaded the model, but I don't know how many times I need
to wait, not any notifications.
I have pulled two times with two different servers but no luck, each time I
met this problem. Could you please let me know what your steps are? Maybe I
could do it as your steps to test it again. Thanks a lot.

one more thing, when I upload an excel file and I click the 'Ingest Data'
button, then I will get a failure message as below.

Unhandled Runtime Error
ReferenceError: response is not defined
"components/ConfigSideNav.js (27:3) @ response

25 | } catch (error) {
26 | setIsLoading(false);

27 | response.text().then(text => {toast.error("Error Ingesting
data."+text);})
| ^
28 | }
29 | };"


[image: image.png]



[image: image.png]



RattyDAVE ***@***.***> 于2023年8月2日周三 20:13写道：

**Comment by RattyDAVE** [comment]
> Thanks so much for your reply. Yes, I do. I downloaded the model, but I don't know how many times I need to wait, not any notifications. I have pull two times with two deffreent servers but no luck, each of time I met this problem. Could you please let me know what's your steps maybe I could do it as your steps to test it again. Thanks a lot.
> 
> one more thing, when I uploaded a excel file and I click 'Ingest Data' button, then I will got a failure message as below.
> 
> Unhandled Runtime Error ReferenceError: response is not defined "components/ConfigSideNav.js (27:3) @ response
> 
> 25 | } catch (error) { 26 | setIsLoading(false);
> 
> > 27 | 	response.text().then(text => {toast.error("Error Ingesting data."+text);})
> > | 	 ^
> > 28 |   }
> > 29 | };"

Excel files are unsupported. You need to convert to CSV!

**Comment by AndyCHENJUN** [comment]
Dear Ratty,

It's a network issue, the model file is not completely downloaded, I
downloaded by manually and it works, Thanks for your support. It's very
slow on my server, one question needs about 1 mins to get answered with a
32GB Ram and 8 core server. I would like to know is that normal or not,
Thank you.

Best Regards.
Andy.

RattyDAVE ***@***.***> 于2023年8月4日周五 21:16写道：
